apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: app
spec:
  containers:
  - name: web
    image: kirilldemtchenko/web-otus:latest
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
#    livenessProbe:
#      exec:
#        command:
#          - 'sh'
#          - '-c'
#          - 'ps aux | grep ps'
#
    livenessProbe:
      tcpSocket: { port: 8080 }
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
    - name: app
      emptyDir: {}

---
apiVersion: v1
kind: Pod
metadata:
  name: init
  labels:
    key: app
spec:
  containers:
  - name: init
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://bit.ly/otus-k8s-index-gen | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
