apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: app
spec:
  containers:
  - name: web
    image: kirilldemtchenko/web-otus:latest
    volumeMounts: 
    - name: app
      mountPath: /app
  volumes:
    - name: app
      emptyDir: {}

---
apiVersion: v1
kind: Pod
metadata:
  name: init
  labels:
    key: app
spec:
  containers:
  - name: init
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
